AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Shrinkify URL

Globals:
  Function:
    Timeout: 3
Parameters:
  DBConnection:
    Type: String
    Default: NA

Resources:
  ShrinkifyURL:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./api
      Handler: main.handler
      Runtime: go1.x
      Timeout: 50
      Events:
        API:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: any
        HTML:
          Type: HttpApi
          Properties:
            Path: /
            Method: get
      Environment:
        Variables:
          DYNAMO_TABLE: !Ref DBConnection

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: shrinkifyurl
      AttributeDefinitions: 
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema: 
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST


Outputs:
  ShrinkifyApi:
    Description: API Gateway endpoint URL for Prod for Shrinkify URL function
    Value:
      Fn::Sub: https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/
  ShrinkifyURLFunction:
    Description: Express Backend Lambda Function ARN
    Value: !Sub ShrinkifyURL.Arn
  ShrinkifyURLIamRole:
    Description: Implicit IAM Role created for Shrinkify URL function
    Value: !Sub ShrinkifyURLFunctionRole.Arn
